const courses = [
    { path: '/accounting', name: 'Accounting' },
    { path: '/aerospace-studies', name: 'Aerospace Studies' },
    { path: '/agribusiness-and-applied-economics', name: 'Agribusiness & Applied Economics' },
    { path: '/agricultural-and-biosystems-engineering', name: 'Agricultural & Biosystems Engineering' },
    { path: '/agricultural-systems-management', name: 'Agricultural Systems Management' },
    { path: '/agriculture-general', name: 'Agriculture General' },
    { path: '/animal-sciences', name: 'Animal Sciences' },
    { path: '/anthropology', name: 'Anthropology' },
    { path: '/biochemistry', name: 'Biochemistry' },
    { path: '/biological-sciences', name: 'Biological Sciences' },
    { path: '/biomedical-engineering', name: 'Biomedical Engineering' },
    { path: '/botany', name: 'Botany' },
    { path: '/business-administration', name: 'Business Administration' },
    { path: '/cereal-and-food-sciences', name: 'Cereal & Food Sciences' },
    { path: '/chemistry', name: 'Chemistry' },
    { path: '/civil-engineering', name: 'Civil Engineering' },
    { path: '/coatings-and-polymeric-materials', name: 'Coatings and Polymeric Materials' },
    { path: '/college-of-health-professions', name: 'College of Health Professions' },
    { path: '/communication', name: 'Communication' },
    { path: '/community-development', name: 'Community Development' },
    { path: '/computer-science', name: 'Computer Science' },
    { path: '/construction-management-and-engineering', name: 'Construction Management & Engineering' },
    { path: '/counselor-education', name: 'Counselor Education' },
    { path: '/criminal-justice', name: 'Criminal Justice' },
    { path: '/economics', name: 'Economics' },
    { path: '/education', name: 'Education' },
    { path: '/electrical-and-computer-engineering', name: 'Electrical & Computer Engineering' },
    { path: '/electrical-engineering', name: 'Electrical Engineering' },
    { path: '/emergency-management', name: 'Emergency Management' },
    { path: '/engineering-general', name: 'Engineering General' },
    { path: '/english', name: 'English' },
    { path: '/entomology', name: 'Entomology' },
    { path: '/entrepreneurship', name: 'Entrepreneurship' },
    { path: '/environment-and-conservation-science', name: 'Environment & Conservation Science' },
    { path: '/environmental-design', name: 'Environmental Design' },
    { path: '/environmental-engineering', name: 'Environmental Engineering' },
    { path: '/finance', name: 'Finance' },
    { path: '/food-safety', name: 'Food Safety' },
    { path: '/french', name: 'French' },
    { path: '/geography', name: 'Geography' },
    { path: '/geology', name: 'Geology' },
    { path: '/german', name: 'German' },
    { path: '/health-nutrition-and-exercise-sciences', name: 'Health, Nutrition & Exercise Sciences' },
    { path: '/history', name: 'History' },
    { path: '/honors', name: 'Honors' },
    { path: '/human-and-community-education', name: 'Human & Community Education' },
    { path: '/human-development-and-family-science', name: 'Human Development & Family Science' },
    { path: '/human-sciences-and-education', name: 'Human Sciences and Education' },
    { path: '/industrial-and-manufacturing-engineering', name: 'Industrial and Manufacturing Engineering' },
    { path: '/international-studies', name: 'International Studies' },
    { path: '/landscape-architecture', name: 'Landscape Architecture' },
    { path: '/management', name: 'Management' },
    { path: '/management-information-systems', name: 'Management Information Systems' },
    { path: '/marketing', name: 'Marketing' },
    { path: '/master-of-business-administration', name: 'Master of Business Administration' },
    { path: '/materials-and-nanotechnology', name: 'Materials & Nanotechnology' },
    { path: '/mathematics', name: 'Mathematics' },
    { path: '/mechanical-engineering', name: 'Mechanical Engineering' },
    { path: '/medical-laboratory-science', name: 'Medical Laboratory Science' },
    { path: '/microbiology', name: 'Microbiology' },
    { path: '/military-science', name: 'Military Science' },
    { path: '/modern-languages', name: 'Modern Languages' },
    { path: '/music', name: 'Music' },
    { path: '/natural-resources-management', name: 'Natural Resources Management' },
    { path: '/new-institutional-social-science', name: 'New Institutional Social Science' },
    { path: '/nursing', name: 'Nursing' },
    { path: '/pharmaceutical-sciences', name: 'Pharmaceutical Sciences' },
    { path: '/pharmacy-practice', name: 'Pharmacy Practice' },
    { path: '/philosophy', name: 'Philosophy' },
    { path: '/physics', name: 'Physics' },
    { path: '/plant-pathology', name: 'Plant Pathology' },
    { path: '/plant-sciences', name: 'Plant Sciences' },
    { path: '/political-science', name: 'Political Science' },
    { path: '/precision-agriculture', name: 'Precision Agriculture' },
    { path: '/psychology', name: 'Psychology' },
    { path: '/public-health', name: 'Public Health' },
    { path: '/radiologic-sciences', name: 'Radiologic Sciences' },
    { path: '/range-science', name: 'Range Science' },
    { path: '/religious-studies', name: 'Religious Studies' },
    { path: '/respiratory-care', name: 'Respiratory Care' },
    { path: '/science-technology-engineering-and-mathematics', name: 'Science, Technology, Engineering, and Mathematics' },
    { path: '/sociology', name: 'Sociology' },
    { path: '/soil-science', name: 'Soil Science' },
    { path: '/spanish', name: 'Spanish' },
    { path: '/statistics', name: 'Statistics' },
    { path: '/supply-chain-management', name:'Supply Chain Management' },
    { path: '/theatre-arts', name: 'Theatre Arts' },
    { path: '/transportation-and-logistics', name: 'Transportation & Logistics' },
    { path: '/tribal-and-indigenous-peoples-studies', name: 'Tribal and Indigenous Peoples Studies' },
    { path: '/university-general', name: 'University, General' },
    { path: '/veterinary-science', name: 'Veterinary Science' },
    { path: '/women-and-gender-studies', name: 'Women and Gender Studies' }
];